Repository NeuralEnsemble/python-neo, pull requests merged in 2018-11, with the labels that each got.

#589 account for empty nse in rawio.neuralynxrawio
  neo/rawio/neuralynxrawio.py
Labels: IO

#587 Change the behaviour of `SpikeTrain.__add__` and `SpikeTrain.__sub__`
  neo/core/spiketrain.py
  neo/test/coretest/test_spiketrain.py
Labels: Core, enhancement

#583 Blackrock - separate dig input and serial input
  neo/rawio/blackrockrawio.py
Labels: IO

#562 Parse EpochSection in ABF2 files to get digital output waveform info
  neo/rawio/axonrawio.py
Labels: IO

#580 OpenEphys reader for legacy format.
  .pep8speaks.yml
  neo/io/__init__.py
  neo/io/openephysio.py
  neo/rawio/openephysrawio.py
  neo/rawio/tests/test_openephysrawio.py
  neo/test/iotest/test_openephysio.py
Labels: New IO Class

#577 [MRG] Implementation of the "raw" Multi Channel System (MCS) IO
  neo/io/__init__.py
  neo/io/rawmcsio.py
  neo/rawio/__init__.py
  neo/rawio/rawmcsrawio.py
  neo/rawio/tests/test_rawmcsrawio.py
  neo/test/iotest/test_rawmcsio.py
Labels: New IO Class

#576 [nixio] New library version 1.5
  .circleci/requirements_testing.txt
  doc/source/install.rst
  neo/io/nixio.py
  neo/rawio/tests/test_nixrawio.py
  neo/test/iotest/test_nixio.py
  setup.py
Labels: IO

#598 Fix Python3 issue in BlackrockIO
  neo/io/blackrockio_v4.py
  neo/test/iotest/test_blackrockio.py
Labels: bug

#593 Intanrawio : both RHD and RHS
  neo/io/__init__.py
  neo/io/intanio.py
  neo/rawio/__init__.py
  neo/rawio/intanrawio.py
  neo/rawio/tests/test_intanrawio.py
  neo/test/iotest/test_intanio.py
Labels: New IO Class

#586 add `Event.to_epoch` method
  neo/core/epoch.py
  neo/core/event.py
  neo/io/nixio.py
  neo/test/coretest/test_epoch.py
  neo/test/coretest/test_event.py
  neo/test/coretest/test_generate_datasets.py
  neo/test/generate_datasets.py
  neo/test/iotest/test_pickleio.py
Labels: Core, enhancement

#600 rtu to fix this overflow.
  neo/rawio/spike2rawio.py
Labels: needs-input

#581 [nixio] Fix in read_block() auto indexing
  neo/io/nixio.py
  neo/test/iotest/test_nixio.py
Labels: IO

#614 Fix and associated test for #613
  neo/core/spiketrain.py
  neo/test/coretest/test_spiketrain.py
Labels: Core, bug

#582 [nixio] Use OrderedDict to group signals
  neo/io/nixio.py
  neo/test/iotest/test_nixio.py
Labels: IO
