Repository NeuralEnsemble/python-neo, pull requests merged in 2019-07, with the labels that each got.

#676 Fix merge behaviour
  neo/core/baseneo.py
  neo/core/container.py
  neo/test/coretest/test_channelindex.py
  neo/test/coretest/test_segment.py
  neo/test/coretest/test_unit.py
  neo/test/tools.py
Labels: bug

#701 Fix some deprecation warnings
  neo/io/baseio.py
  neo/io/tools.py
  neo/test/coretest/test_base.py
  neo/test/coretest/test_dataobject.py
Labels: task

#662 Fix Nix Ignoring Array Annotations
  neo/io/nixio.py
  neo/test/iotest/test_nixio.py
Labels: IO

#655 Change of the logic for version handling in neuralynx because of "pag…
  neo/rawio/neuralynxrawio.py
Labels: needs-input

#716 Acknowledgements
  doc/source/authors.rst
Labels: Documentation

#718 Add list of implemented RawIO classes to docs
  doc/source/io_developers_guide.rst
  doc/source/rawio.rst
  neo/io/__init__.py
  neo/rawio/__init__.py
  neo/rawio/blackrockrawio.py
  neo/rawio/openephysrawio.py
Labels: Documentation

#706 Improve consistency between Epoch, Event and SpikeTrain
  neo/core/epoch.py
  neo/core/event.py
  neo/test/coretest/test_epoch.py
  neo/test/coretest/test_event.py
Labels: enhancement
