Repository NeuralEnsemble/python-neo, pull requests merged in 2020-11, with the labels that each got.

#887 Deprecate old Blackrock and Neuralynx IOs
  neo/io/blackrockio_v4.py
  neo/io/neuralynxio_v1.py
Labels: blocker

#817 Replace ChannelIndex and Unit by View and Group
  doc/source/core.rst
  doc/source/grouping.rst
  doc/source/images/base_schematic.png
  doc/source/images/base_schematic.svg
  doc/source/images/base_schematic_with_IrregularlySampledSignal.svg
  doc/source/images/generate_diagram.py
  doc/source/images/multi_segment_diagram.svg
  doc/source/images/multi_segment_diagram_spiketrain.png
  doc/source/images/multi_segment_diagram_spiketrain.svg
  doc/source/scripts/multi_tetrode_example.py
  doc/source/scripts/spike_sorting_example.py
  doc/source/usecases.rst
  neo/converter.py
  neo/core/__init__.py
  neo/core/analogsignal.py
  neo/core/baseneo.py
  neo/core/block.py
  neo/core/channelindex.py
  neo/core/group.py
  neo/core/segment.py
  neo/core/unit.py
  neo/core/view.py
  neo/io/basefromrawio.py
  neo/io/baseio.py
  neo/io/brainwaredamio.py
  neo/io/brainwaref32io.py
  neo/io/brainwaresrcio.py
  neo/io/nixio.py
  neo/io/proxyobjects.py
  neo/io/tools.py
  neo/rawio/baserawio.py
  neo/test/coretest/test_block.py
  neo/test/coretest/test_generate_datasets.py
  neo/test/coretest/test_group.py
  neo/test/coretest/test_view.py
  neo/test/generate_datasets.py
  neo/test/iotest/test_axographio.py
  neo/test/iotest/test_blackrockio.py
  neo/test/iotest/test_brainwaredamio.py
  neo/test/iotest/test_brainwaref32io.py
  neo/test/iotest/test_brainwaresrcio.py
  neo/test/iotest/test_exampleio.py
  neo/test/iotest/test_neuralynxio.py
  neo/test/iotest/test_nixio.py
  neo/test/rawiotest/rawio_compliance.py
  neo/test/test_converter.py
  neo/test/tools.py
Labels: blocker, enhancement

#806 Support Empty Array Annotations in NixIO
  neo/io/nixio.py
  neo/test/iotest/test_nixio.py
Labels: blocker

#871 Release notes for v0.9.0
  LICENSE.txt
  README.rst
  doc/source/conf.py
  doc/source/core.rst
  doc/source/grouping.rst
  doc/source/releases/0.9.0.rst
  doc/source/whatisnew.rst
  neo/core/view.py
  neo/version.py
Labels: Documentation, blocker
