Repository NeuralEnsemble/python-neo, pull requests merged in 2020-09, with the labels that each got.

#859 Changes related to the `IO.read()` method
  doc/source/core.rst
  neo/io/asciiimageio.py
  neo/io/baseio.py
  neo/io/blkio.py
  neo/io/brainwaredamio.py
  neo/io/brainwaref32io.py
  neo/io/brainwaresrcio.py
  neo/io/tiffio.py
  neo/test/iotest/test_brainwaredamio.py
  neo/test/iotest/test_brainwaref32io.py
  neo/test/iotest/test_brainwaresrcio.py
Labels: Documentation, IO

#858 Fixes #757
  neo/core/analogsignal.py
  neo/core/imagesequence.py
  neo/test/coretest/test_analogsignal.py
Labels: Core, bug

#837 Default group mode to 'group-by-same-units'
  neo/io/axographio.py
  neo/io/axonio.py
  neo/io/basefromrawio.py
  neo/io/bci2000io.py
  neo/io/brainvisionio.py
  neo/io/elanio.py
  neo/io/neuroexplorerio.py
  neo/io/nixio_fr.py
  neo/io/plexonio.py
  neo/io/rawbinarysignalio.py
  neo/io/tdtio.py
  neo/io/winedrio.py
  neo/io/winwcpio.py
  neo/test/iotest/test_axographio.py
  neo/test/iotest/test_exampleio.py
Labels: blocker
