Repository NeuralEnsemble/python-neo, pull requests merged in 2020-10, with the labels that each got.

#884 Make segment time evaluation compatible with ProxyObjects
  neo/core/segment.py
  neo/test/coretest/test_segment.py
Labels: bug

#886 Vectorize AnalogSignal.time_index()
  neo/core/analogsignal.py
  neo/test/coretest/test_analogsignal.py
Labels: Core, enhancement

#851 Fixes to make tests pass with Pegasus event files only directory.
  .gitignore
  neo/rawio/neuralynxrawio.py
  neo/test/iotest/test_neuralynxio.py
Labels: IO
