Repository NeuralEnsemble/python-neo, pull requests merged in 2021-06, with the labels that each got.

#965 Remove deprecated classes (ChannelIndex, Unit) and IOs; simplify tests
  neo/converter.py
  neo/core/__init__.py
  neo/core/analogsignal.py
  neo/core/baseneo.py
  neo/core/basesignal.py
  neo/core/block.py
  neo/core/channelindex.py
  neo/core/group.py
  neo/core/irregularlysampledsignal.py
  neo/core/segment.py
  neo/core/spiketrain.py
  neo/core/unit.py
  neo/io/alphaomegaio.py
  neo/io/basefromrawio.py
  neo/io/baseio.py
  neo/io/brainwaref32io.py
  neo/io/brainwaresrcio.py
  neo/io/elphyio.py
  neo/io/klustakwikio.py
  neo/io/kwikio.py
  neo/io/nixio.py
  neo/io/nixio_fr.py
  neo/io/proxyobjects.py
  neo/io/tools.py
  neo/rawio/baserawio.py
  neo/rawio/blackrockrawio.py
  neo/rawio/nixrawio.py
  neo/test/coretest/test_analogsignal.py
  neo/test/coretest/test_block.py
  neo/test/coretest/test_channelindex.py
  neo/test/coretest/test_epoch.py
  neo/test/coretest/test_event.py
  neo/test/coretest/test_generate_datasets.py
  neo/test/coretest/test_group.py
  neo/test/coretest/test_irregularysampledsignal.py
  neo/test/coretest/test_segment.py
  neo/test/coretest/test_spiketrain.py
  neo/test/coretest/test_unit.py
  neo/test/generate_datasets.py
  neo/test/iotest/test_blackrockio.py
  neo/test/iotest/test_neuralynxio.py
  neo/test/iotest/test_nixio.py
  neo/test/iotest/test_nixio_fr.py
  neo/test/iotest/test_pickleio.py
  neo/test/test_converter.py
  neo/test/tools.py
Labels: Core, IO, blocker

#996 Fix MEArec indexing when channel_indexes are unsorted
  neo/rawio/mearecrawio.py
Labels: blocker

#987 Ced sonpy implementation
  neo/io/__init__.py
  neo/io/cedio.py
  neo/rawio/__init__.py
  neo/rawio/cedrawio.py
  neo/rawio/spike2rawio.py
  neo/test/iotest/test_cedio.py
  neo/test/rawiotest/test_cedrawio.py
  requirements_testing.txt
Labels: IO

#982 simple fix for spike2io
  neo/rawio/spike2rawio.py
Labels: IO

#991 Remove some np.int and np.float because of numpy 0.20.0
  neo/core/analogsignal.py
  neo/core/spiketrain.py
  neo/io/alphaomegaio.py
  neo/io/brainwaredamio.py
  neo/io/klustakwikio.py
  neo/io/tiffio.py
  neo/test/coretest/test_base.py
  neo/test/coretest/test_spiketrain.py
  neo/test/iotest/test_nestio.py
  neo/test/iotest/test_nixio.py
Labels: blocker

#985 Maxwell rawio implementation
  neo/io/__init__.py
  neo/io/maxwellio.py
  neo/rawio/__init__.py
  neo/rawio/maxwellrawio.py
  neo/test/iotest/test_maxwellio.py
  neo/test/rawiotest/test_maxwellrawio.py
Labels: IO, New IO Class

#986 Enable AxonaIO to read spiketimes and waveforms
  neo/rawio/axonarawio.py
  neo/test/iotest/test_axonaio.py
  neo/test/rawiotest/test_axonarawio.py
Labels: IO

#1000 Implement SpikeTrainList class, and make Segment.spiketrains an instance of this class
  neo/core/container.py
  neo/core/segment.py
  neo/core/spiketrain.py
  neo/core/spiketrainlist.py
  neo/test/coretest/test_segment.py
  neo/test/coretest/test_spiketrainlist.py
  neo/test/generate_datasets.py
  neo/test/tools.py
Labels: Core, enhancement

#970 Comments on stream implementation and its implications.
  neo/rawio/baserawio.py
  neo/rawio/neuralynxrawio/neuralynxrawio.py
Labels: Documentation, discussion
