Repository NeuralEnsemble/python-neo, pull requests merged in 2022-05, with the labels that each got.

#1035 Add EDF IO
  neo/io/__init__.py
  neo/io/edfio.py
  neo/rawio/__init__.py
  neo/rawio/edfrawio.py
  neo/test/iotest/test_edfio.py
  neo/test/rawiotest/test_edfrawio.py
  requirements_testing.txt
  setup.py
Labels: New IO Class

#1051 Fix exception raised when calling pyplot.plot(sig.times, sig) if the signal has array annotations
  neo/core/analogsignal.py
  neo/test/coretest/test_analogsignal.py
Labels: bug

#1112 SpikeTrainList improvements
  neo/core/spiketrainlist.py
  neo/test/coretest/test_spiketrainlist.py
Labels: bug, enhancement, Core
