Repository NeuralEnsemble/python-neo, pull requests merged in 2023-07, with the labels that each got.

#1311 Check the types of objects added to a container with the new `add()` method
  doc/source/authors.rst
  neo/core/container.py
  neo/core/group.py
  neo/test/coretest/test_block.py
  neo/test/coretest/test_group.py
  neo/test/coretest/test_segment.py
Labels: enhancement

#1267 [Tdt] Raise error in case no valid tdt structure was found
  neo/rawio/tdtrawio.py
Labels: enhancement, IO

#1288 Add MED wrapper
  neo/io/__init__.py
  neo/io/medio.py
  neo/rawio/__init__.py
  neo/rawio/medrawio.py
  neo/test/iotest/test_medio.py
  neo/test/rawiotest/test_medrawio.py
  pyproject.toml
Labels: New IO Class
