Repository NeuralEnsemble/python-neo, pull requests merged in 2023-05, with the labels that each got.

#1271 Use igor2 in place of igor
  doc/source/install.rst
  neo/io/igorproio.py
  neo/test/iotest/test_igorio.py
  pyproject.toml
Labels: IO

#1272 Remove pickle python 2 library
  neo/io/pickleio.py
Labels: enhancement

#1274 [AsciiIO] Fix handling of handle channel index array annotations
  neo/io/asciisignalio.py
  neo/test/iotest/test_asciisignalio.py
Labels: bug, IO

#1251 Add codemeta.json
  codemeta.json
Labels: enhancement, Documentation
