Repository NeuralEnsemble/python-neo, pull requests merged in 2024-01, with the labels that each got.

#1374 Fix signal inversion in BioCAM IO
  neo/rawio/biocamrawio.py
Labels: bug

#1373 Add workflow actions for automated release to PyPI
  .github/workflows/publish-to-pypi-test.yml
  .github/workflows/publish-to-pypi.yml
Labels: continuous-integration

#1361 Fix some tests that fail when running locally
  neo/test/coretest/test_analogsignal.py
  neo/test/coretest/test_irregularysampledsignal.py
  neo/test/iotest/test_bci2000io.py
  neo/test/iotest/test_medio.py
  neo/test/iotest/test_plexon2io.py
  neo/test/rawiotest/test_cedrawio.py
  neo/test/rawiotest/test_medrawio.py
  neo/test/rawiotest/test_plexon2rawio.py
Labels: defect

#1313 make the handling of RegionOfInterest subclasses consistent with ChannelView
  neo/core/baseneo.py
  neo/core/block.py
  neo/core/group.py
  neo/core/imagesequence.py
  neo/core/regionofinterest.py
  neo/test/coretest/test_group.py
  neo/test/coretest/test_imagesequence.py
  neo/test/coretest/test_regionofinterest.py
Labels: defect

#1380 Retrieve correct tag in test pypi action
  .github/workflows/publish-to-pypi-test.yml
Labels: continuous-integration

#1376 Add black-formatting action
  .github/workflows/black-formatting.yml
  .github/workflows/io-test.yml
  pyproject.toml
Labels: continuous-integration
