Repository NeuralEnsemble/python-neo, pull requests merged in 2024-02, with the labels that each got.

#1386 Improved support for saving/loading Groups in NeoMatlabIO
  neo/core/baseneo.py
  neo/core/container.py
  neo/core/regionofinterest.py
  neo/core/spiketrainlist.py
  neo/core/view.py
  neo/io/neomatlabio.py
  neo/test/coretest/test_block.py
  neo/test/generate_datasets.py
  neo/test/iotest/test_neomatlabio.py
Labels: IO, Core

#1384 Updated "generate_diagram.py" script
  doc/source/images/generate_diagram.py
  doc/source/images/simple_generated_diagram.png
  doc/source/images/simple_generated_diagram.svg
Labels: Documentation

#1391 Release notes for 0.13.0
  LICENSE.txt
  README.rst
  doc/old_stuffs/developers_guide.rst
  doc/source/conf.py
  doc/source/releases.rst
  doc/source/releases/0.12.0.rst
  doc/source/releases/0.13.0.rst
  neo/test/README.txt
Labels: Documentation

#1399 Check that keys of nested dictionaries in annotations are `str`
  neo/core/baseneo.py
Labels: Core

#1407 TDTRawIO: Change tdt units to uV
  neo/rawio/tdtrawio.py
Labels: bug, IO

#1397 Add and unify many docstrings
  neo/io/basefromrawio.py
  neo/io/baseio.py
  neo/rawio/alphaomegarawio.py
  neo/rawio/axographrawio.py
  neo/rawio/axonarawio.py
  neo/rawio/axonrawio.py
  neo/rawio/baserawio.py
  neo/rawio/bci2000rawio.py
  neo/rawio/biocamrawio.py
  neo/rawio/blackrockrawio.py
  neo/rawio/brainvisionrawio.py
  neo/rawio/cedrawio.py
  neo/rawio/edfrawio.py
  neo/rawio/elanrawio.py
  neo/rawio/intanrawio.py
  neo/rawio/maxwellrawio.py
  neo/rawio/mearecrawio.py
  neo/rawio/medrawio.py
  neo/rawio/micromedrawio.py
  neo/rawio/neuralynxrawio/neuralynxrawio.py
  neo/rawio/neuroscoperawio.py
  neo/rawio/nixrawio.py
  neo/rawio/openephysrawio.py
  neo/rawio/phyrawio.py
  neo/rawio/plexon2rawio/plexon2rawio.py
  neo/rawio/plexonrawio.py
  neo/rawio/rawbinarysignalrawio.py
  neo/rawio/rawmcsrawio.py
  neo/rawio/spike2rawio.py
  neo/rawio/spikegadgetsrawio.py
  neo/rawio/spikeglxrawio.py
  neo/rawio/tdtrawio.py
  neo/rawio/winedrrawio.py
  neo/rawio/winwcprawio.py
Labels: enhancement

#1403 NeuralynxIO: get_file_map as static method
  neo/rawio/neuralynxrawio/neuralynxrawio.py
Labels: IO
